language: ruby
sudo: false

cache:
  - bundler

rvm:
  - 2.4.0

before_script:
  - RAILS_ENV=test bundle exec rake db:create --trace
  - cp config/secrets.yml.travis config/secrets.yml

script:
  - RAILS_ENV=test bundle exec rake db:migrate --trace
  - bundle exec rake test
