language: ruby
sudo: false

rvm:
  - 2.4.0
  - ruby-head

services:
  - mysql

before_script:
  - RAILS_ENV=test bundle exec rake db:create --trace

script:
  - RAILS_ENV=test bundle exec rake db:migrate --trace
  - bundle exec rake test
